apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ppa-knative
spec:
  template:
    spec:
      containers:
        - image: PROJECT/IMAGE_PPA
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-svc"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-confmap
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-confmap
                  key: postgres_db