apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:

  - manifests/ping-pong-knative.yaml
  - manifests/log-knative.yaml
  - manifests/greeter-knative.yaml
  - manifests/confmap_postgres.yaml
  - manifests/secret_postgres.yaml
  - manifests/service_postgres.yaml
  - manifests/statefulset.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/confmap_log.yaml

images:
  - name: PROJECT/IMAGE_LOR
    newName: skinatro/log-output-read

  - name: PROJECT/IMAGE_LOG
    newName: skinatro/log-output-gen

  - name: PROJECT/IMAGE_PPA
    newName: skinatro/ping-pong-app

  - name: PROJECT/IMAGE_GRE
    newName: skinatro/greeter
