apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/gateway-istio.yaml
  - manifests/deployment_log.yaml
  - manifests/deployment_pong.yaml
  - manifests/deployment_greeter-v1.yaml
  - manifests/deployment_greeter-v2.yaml
  - manifests/configmap_log.yaml
  - manifests/confmap_postgres.yaml
  - manifests/secret_postgres.yaml
  - manifests/service_log.yaml
  - manifests/service_pong.yaml
  - manifests/service_greeter-v1.yaml
  - manifests/service_greeter-v2.yaml
  - manifests/service_postgres.yaml
  - manifests/statefulset.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/virtualservice.yaml
  - manifests/service_greeter-frontdoor.yaml

images:
  - name: PROJECT/IMAGE_LOR
    newName: skinatro/log-output-read

  - name: PROJECT/IMAGE_LOG
    newName: skinatro/log-output-gen

  - name: PROJECT/IMAGE_PPA
    newName: skinatro/ping-pong-app

  - name: PROJECT/IMAGE_GRE
    newName: skinatro/greeter
